[pytest]
addopts= -v  --html="report/HTML_report.html"
markers=
    great: Tests that compare using greater than symbol
    less: Tests that compare using less than symbol
    activity: dfd

    smoke: basic tests
    regression: edge case tests
    hardware: hardware-related tests
    software_logic: logic tests
    brightness: brightness-related tests